# Generated by Django 5.1.2 on 2024-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254)),
                ('flavor_suggestion', models.CharField(max_length=50)),
                ('allergy_concern', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('seasonal', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
    ]
