# Generated by Django 5.1.2 on 2024-11-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavors',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
